### PR TITLE
Some fixes for chapter 2

### PR DESCRIPTION
**Pull request by jfmengels**
Some fixes for chapter 2.
Mostly syntax errors that made examples non-copy-pastable in a console and a few code blocks that were not marked a JavaScript.

### CODE REVIEW

**Comment by getify** [comment]
I appreciate the fixes to marking the code blocks with `js`, but the "fixes" to the code aren't what I want. Neither of those two snippets are intended to be copy-pastable, as they're incomplete and only illustrative.

The places where `..` shows at the beginning of a line, I should probably make those `// ..`, but they're intended to show that more code has been elided. Same with the `..` in the arguments list of `send`... it should probably be `send( /* .. */ )`.

**Comment by getify** [comment]
And the omissions of `function` are intentional because these are replacements for the concise methods in the earlier snippet.

**Comment by getify** [comment]
Thanks for pointing out the mistakes. I corrected them with that commit. :)

**Comment by jfmengels** [comment]
No problem ;)

**Pull request closed without merging**
