### PR TITLE
ch4: fixing compose implementation bug

### LINKED ISSUE #146: "compose" function implementation bugs in chapter 4.
This afternoon, I tried implement myself a `compose` function follow this: 
```
function compose(...fns) {
    return function composed(result){
        return fns.reverse().reduce( function reducer(result,fn){
            return fn( result );
        }, result );
    };
}

// or the ES6 => form
var compose = (...fns) =>
    result =>
        fns.reverse().reduce(
            (result,fn) =>
                fn( result )
            , result
        );
```
I found that this `compose` function always give me wrong result. The reason is that `reverse` function mutates the `fns` array and our `fns` array is kept in closure.

Here is my code snippet:
```
const computeTaxForIncome = compose(computeTax, computeTaxedIncome);

console.log(computeTaxForIncome(14000000));
console.log(computeTaxForIncome(18000000));
console.log(computeTaxForIncome(20000000));
console.log(computeTaxForIncome(25000000));
console.log(computeTaxForIncome(50000000));
```

Stack trace when run the `computeTaxForIncome` function: 
```
[ [Function: computeTax], [Function: computeTaxedIncome] ]
14000000
5000000
250000
[ [Function: computeTaxedIncome], [Function: computeTax] ]
18000000
1950000
-7050000
[ [Function: computeTax], [Function: computeTaxedIncome] ]
20000000
11000000
900000
[ [Function: computeTaxedIncome], [Function: computeTax] ]
25000000
3350000
-5650000
[ [Function: computeTax], [Function: computeTaxedIncome] ]
50000000
41000000
7000000
```

My suggestion is adding `slice` function to the implementation to avoid mutating the `fns` array. 
```
var compose = (...fns) =>
    result =>
        fns.slice().reverse().reduce(
            (result,fn) =>
                fn( result )
            , result
        );
```
I will make a pull request for this issue when I have free time.

### PR DESCRIPTION
**Pull request by darkamenosa**
This commit fixes #146

### CODE REVIEW

**Comment by getify** [comment]
Thanks for finding and fixing this bug.

However, rather than fixing this with `slice()`, I'd rather fix it by saying `[...fns].reverse().reduce(..)`. And btw, this code is repeated/quoted in chapter 9, so it needs to be fixed there, too. :)

**Comment by darkamenosa** [comment]
I have changed the implementation follow your recommendation and updated chapter 9. Thanks for reminding me.

**Comment by DScheglov** [comment]
Hi, I guess if we are using spread to splice the array, so we could use the `reduceRight` to avoid `reverse` and `slice` at all, am I wrong? :)

@getify, thanks a lot for the Book.

**Comment by getify** [comment]
@DScheglov this is intentionally not done here because we come back to the topic of `compose(..)` in ch9 when we talk about list operations, and we illustrate `reduceRight(..)` there.

**Comment by getify** [comment]
Thanks so much!

**Pull request merged**
