### PR TITLE
Update ch1.md

### PR DESCRIPTION
**Pull request by jordalgo**
Yes, I promise I've read the [Contributions Guidelines](CONTRIBUTING.md).

Add sanctuary and fantasy-land to libraries list.

### CODE REVIEW

**Comment by getify** [comment]
These resources might very well deserve mention in the book (and maybe even the chapter) but I don't think I'd classify them (esp FL, I don't know about sanctuy) as "the place to start" which is what this specific list is.

FL is kind of exactly the opposite of this book's approach. It's formalism and terminology and notation to the maximum. If I were recommending FL, I'd be recommending it as where to turn *after* you've finished this book and feel very comfortable with all its concepts.

I think this detail needs different treatment than to just add it to a list for the sake of completeness.

**Comment by jordalgo** [comment]
@getify Yah, I agree, Fantasy Land is definitely not first chapter 👍 But when I was starting out with FP in javascript, Sanctuary was a great find and it was quite a revelation to start using the Maybe type. Obviously it's your call, just wanted to include some resources that have helped me with FP.

**Comment by getify** [comment]
This is still under consideration. I think I'd rather mention these more advanced resources in Appendix C about FP libraries.

**Comment by jordalgo** [comment]
@getify Whatever works. Let me know if you want me to create a new PR or just close this one and add them yourself 👍

**Comment by getify** [comment]
Addressed in https://github.com/getify/Functional-Light-JS/commit/7c97ff4423beb54916ce70015ccf6cffd0abd28c

**Pull request closed without merging**
