### PR TITLE
Add a remark about generators to ch1.md

### PR DESCRIPTION
**Pull request by flashhhh**

### CODE REVIEW

**Comment by getify** [comment]
Hmmmm... that might be useful but it also might be a pandoras box I'm opening. Frankly, I'm not sure at all how FPrs think about generators. Given that it's changing state over time, seems more likely to be frowned on FP-wise than embraced. Shrugs.

**Comment by flashhhh** [comment]
Generators are totally no use for FPrs, but I'd suggest to add this remark just for the picture fullness. It might be relevant to add something like "which are not a part of the FP" at the end.

It just would be too unfair not to mention generators when talking about returning of multiple values at all. At least, I guess so.

**Comment by getify** [comment]
I'll keep this idea around and under consideration. Thanks.

**Comment by flashhhh** [comment]
Ok, I'm closing this PR then. Thank you!

**Pull request closed without merging**
