### PR TITLE
Added a foreword

### PR DESCRIPTION
**Pull request by DrBoolean**
Happy to shorten or revise a bit! Let me know :)

### CODE REVIEW

**Comment by getify** [comment]
I love it. I'm so honored by what you wrote. Thank you so much! :)

**Comment by DrBoolean** [comment]
Awesome! 😄

**Comment by getify** [comment]
Do you want the link of your name (in the README / table of contents) to be to your twitter page?

**Comment by DrBoolean** [comment]
Whatever's totally fine - github, twitter. Thanks!

**Pull request merged**
