### PR TITLE
Functional programming IS just functions

### PR DESCRIPTION
**Pull request by puffnfresh**

### CODE REVIEW

**Comment by getify** [comment]
I think we're saying much the same thing, just I'm spending a whole chapter to explain why "function" means something different than most readers who will pick up my text think. Specifically, many more of my audience who would say "FP is just functions" mean "FP is just procedures" and not "FP is just real functional functions". The point of this chapter is to clear that up.

**Comment by puffnfresh** [comment]
@getify I have a lot of experience teaching FP. This statement will confuse people:

> Functional Programming is not just programming with functions.

Especially since it's *exactly the opposite* of what I teach.

It needs to be fixed.

**Comment by tonymorris** [comment]
It's really important to acknowledge that the same thing is definitely not being said. This can be determined by observing the disparity in the success of the outcome in each case. It is not zero. It is not small. It is large and significant.

**Comment by getify** [comment]
The sentence taken in isolation would confuse people. But there's a sentence right after that the provides the nuance that sets up the message I spend the rest of the chapter making, which is in fact that FP is about using **real functions** the way their intended to be defined and used.

**Comment by tonymorris** [comment]
This is not true, as has been observed in the 100% of the cases that I have seen, teaching FP for the previous 15 years. The same is true for my colleagues, peers and friends who understand and teach the subject.

If there is some new insight, that we have all overlooked, please demonstrate it.

**Comment by puffnfresh** [comment]
@getify it goes like:

* FP is not just functions
* And you probably don't know what a function is

But the second one part should be emphasised, but the first needs to be recovered. It needs to be:

* FP IS JUST FUNCTIONS
* But you probably don't know what a function is

**Comment by getify** [comment]
I will take it under advisement that this sentence irks some readers who are already experienced FPers and experienced FP teachers. I may very well tweak the wording to make the point I'm trying to make clearer.

I would note however that my audience is people who known next to nothing about FP, so my style is to ease them into realizations rather than beat them over the head with them.

**Comment by puffnfresh** [comment]
@getify that is also my audience. I have experience in this. I believe you are doing a disservice.

**Comment by tonymorris** [comment]
We are speaking on behalf of your audience, not because we are "irked." We aren't. The sentence is wrong, and does not help your audience.

**Comment by getify** [comment]
@puffnfresh:

what it really says is:

* FP is not just functions
* **because** what you think is a function isn't a function
* so here's what a function really is
* and FP is just those

**Comment by tonymorris** [comment]
"FP very definitely is functions, and if you do not already know that, you are now even more confused. Sorry about that."

**Comment by getify** [comment]
I am not unclear on the point both of you are making. I respect both of your experience. I think we agree more than we disagree, but I realize you're insisting otherwise.

I believe this book will do the service to the audience that I want it to. It's an incomplete first draft, and I will improve it over time. Your feedback is valuable in doing so. Thank you for pointing out that improvement can be made.

**Comment by tonymorris** [comment]
We are stating with high confidence that these (incorrect) sentences are very damaging to the audience. The idea that such false statements are helpful intermediate steps to assist an audience toward a goal is not only not true, but against the interests of any potential audience. It sets them backwards. Had they not read the sentence/concept, they would be further ahead.

I have extremely high confidence in this. I can make predictions based on it. I can test it.

**Comment by tonymorris** [comment]
Here is one (of many) ways such damage is caused.

First, I read the sentence and I know immediately that it is not true. Not only is it not true, but it is not helpful, even as an approximation. I think to myself, "hey maybe I could learn something here, but that is going to very difficult. It is difficult because I am going to have to put in extra effort to differentiate true things, from false things that masquerade as helpful things."

So, you might argue, I am not the audience. This is what happens next.

Bob, who is not quite sure what all this means, reads the sentence and thinks, "wait a minute, that paper I read last week said quite the opposite!" and now Bob doesn't know who to trust, so Bob asks around. Bob is at a fork in the road at this point. His potential to learn is about to be seriously harmed, or advanced. If Bob happens to ask consult an inappropriate source, he risks going down a rabbit hole of disinformation from which recovery is extremely difficult. I see it too often; a claim of understanding of a subject, yet when tested at the most trivial or fundamental hurdle, I see consistent failure. Bob risks falling into this trap.

More to the point, Bob should not be having to decide who and what to trust. Surely we can agree that disinformation already plagues the industry immensely. Rather than lament on it, or concede to it by contributing ourselves, let's just work together to help all the Bobs by not setting traps for them.

**Comment by gabejohnson** [comment]
@getify Perhaps you could change the wording to "Functional Programming is not just programming with `function`"

**Comment by raganwald** [comment]
Folks:

When giving feedback, be relentless in making sure that @getify understands what you are saying, and why. After that, his agreement or action is his problem. Do not persist in trying to ensure he agrees. Do not arrogantly assume that your point is so axiomatic that anyone who disagrees must necessarily not understand.

@getify:

The same is true for you. Seek to fully understand what is being said, and why. Demonstrate your understanding without distracting the discussion with whether you agree.

IMHO, you do not do a disservice to your readers to advocate heterodox positions, provided you are thoroughly clear about what the orthodox position is, and what it offers.

**Comment by getify** [comment]
@raganwald FWIW, I still don't believe my message is "heterodox". I'm coming at this from a different angle and with a different teaching style than is clearly the common one in FP. But I still believe I'm saying the same thing in spirit. And I believe the book, when finished and taken on the whole, will get that across.

**Comment by DrBoolean** [comment]
Since, in FP, we encode ideas from mathematics, the community relies on discipline to ensure properties are held and the definitions are not diluted. Everyone's libraries compose, new discoveries are made that build upon that theory, and our applications maintain their equational reasonability, if that's a word.

It makes sense to fight hard for correctness because without it, we'd lose the world that interops effortlessly - it's a fragile thing and someone might poison the well, so to speak.

I just wanted to bring some background as to why there is passion behind the issue.

**Comment by raganwald** [comment]
@DrBoolean:

> It makes sense to fight hard for correctness

Where JavaScript is concerned, that ship has sailed and was sunk with all hands, long ago. If you wish to tilt at windmills, carry on. You clearly understand what I was saying, and that is enough for me.

**Comment by DrBoolean** [comment]
@raganwald Haha, indeed.

**Comment by DrBoolean** [comment]
I understand the implications of the title page offering an incorrect definition of the paradigm if one were to not read further, but @getify seems to understand and want to explain it in steps.

Brian and Tony are two of the best functional programmers around. They also have experience in the scala community, who typically have JAVA OO backgrounds and approach problems similarly to this books audience. I value their opinion very much.

Anyways, maybe put a * and footnote next to the sentence?

**Comment by getify** [comment]
I've tweaked the wording [here](4e1d7e0cf47100300ab8a79a977ab391c7586244) based on feedback from this thread.

**Comment by puffnfresh** [comment]
@getify thanks :+1:

**Pull request closed without merging**
